- hosts: ansible
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Start service httpd
      services:
        name: httpd
        state: started
        enabled: yes    

- name: Download 
  get_url:
    url: https://www.free-css.com/assets/files/free-css-templates/download/page293/chocolux.zip
    dest: git@github.com:MiraRay13/ansible-task-01.git
    mode: '0440'
