- name: Ansible Task
  hosts: centos
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Start Apache
      service:
        name: httpd
        state: started
        
        enabled: yes
    - name: Download Template
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page294/namari.zip
        dest: /etc/foo.conf  
        mode: '0440' 
    - name: Install unzip
      yum:
        name: unzip
        state: present
    - name: Extract Template
      unarchive:
        src: /etc/foo.conf
        dest: /var/www/html/
        remote_src: yes
    - name: Recursive change ownership or directory
      file:
        path: /var/www/html
        state: directory
        recurse: yes 