- name: Disable SELinux
  selinux:
    state: disabled

- hosts: ansible
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start service httpd
      services:
        name: httpd
        state: started
        enabled: yes    